title: Style Guide Demo
description: This is a demo of the style guide.
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "mint" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

defaults:
    # _docs
    - scope:
        path: ""
        type: docs
      values:
        sidebar:
          nav: "docs"
plugins: 
    - jekyll-include-cache