title: Style Guide Demo
description: This is a demo of the style guide.
theme: minimal-mistakes-jekyll
defaults:
    # _docs
    - scope:
        path: ""
        type: docs
      values:
        sidebar:
          nav: "docs"
plugins: jekyll-include-cache