title: Style Guide Demo
description: This is a demo of the style guide.
theme: jekyll-theme-minimal
defaults:
    # _docs
    - scope:
        path: ""
        type: docs
      values:
        sidebar:
          nav: "docs"
