remote_theme: pages-themes/slate@v0.2.0
plugins:
    - jekyll-remote-theme
title: Style Guide Demo
description: This is a demo of the style guide.
defaults:
    # _docs
    - scope:
        path: ""
        type: docs
      values:
        sidebar:
          nav: "docs"
